name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
      - name: Compile and Pack
        run: |
          cd src | find . -name '*.java' | xargs javac
          cd src | find . -name '*.class' | xargs jar cvmf ./META-INF/MANIFEST.MF Compiler.jar
      - name: Set Date Time
        if: ${{ contains(github.event.head_commit.message, 'release') }}
        id: datetime
        run: |
          echo "date=`date +'%Y/%m/%d'`" >> $GITHUB_OUTPUT
          echo "time=`date +'%H:%M:%S'`" >> $GITHUB_OUTPUT
          echo "datetime=`date +'%Y/%m/%d %H:%M:%S'`" >> $GITHUB_OUTPUT
      - name: Create Release
        if: ${{ contains(github.event.head_commit.message, 'release') }}
        uses: softprops/action-gh-release@v1
        with:
          name: Yuelin's Compiler
          prerelease: false
          draft: false
          tag_name: Tag-${{ steps.datetime.outputs.date }}
          files: |
            Compiler.jar
            LICENSE
